---
title: "Waterhemp - Master Thesis"
author: "Nikola Arsenijevic"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(drc)
library(ggplot2)
library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)
library(plotly)
library(plotrix)
library(htmltools)
library(ggthemes)
```

```{r}
data = read_csv("waterhemp-new-final.csv")

data$crop=factor(data$crop, 
                 levels = c("corn", "narrow", "wide", "fallow"), 
                 labels = c("Corn", "38 cm soybean", "76 cm soybean", "Fallow (Control)"))

options(scipen = 999)
```

## Roughly plotting the data, to view the overall look of it (weight).
```{r echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data, 
       aes(x = tpl_1, 
           y=weight_reduction_crop, 
           color=crop, size = weight_g)) + 
  geom_jitter(alpha = 0.15) + 
  theme_classic() +
  xlab("Transplanting period (days)") +
  ylab("Waterhemp weight") +
  ylim(-25,110)
```



## Fitting the 'drm' model for waterhemp weight reduction
```{r echo=TRUE, message=FALSE, warning=FALSE}
weight_drm1 = drm(data=data, weight_reduction_crop ~ tpl_1, crop, fct = W2.4(fixed = c(NA,0,100,NA), names = c("slope","lower", "upper", "ec50")))

summary(weight_drm1)

plot(weight_drm1, type="all", log = "", ylim=c(0,100))

```


```{r message=FALSE, warning=FALSE}
mselect(weight_drm1, list(l3(), l4(), W1.3(), W2.3(), W1.4(), W1.4(), W2.4()),
nested = F,
sorted = c("IC", "Res var", "Lack of fit", "no"),
linreg = F, icfct = AIC)
```

## Estimating ED50 and ED90 values for weight reduction. Also, comparing the slopes of corn, 15in and 30in soybean.
```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=FALSE}
ED(weight_drm1, c(50,90), type="absolute", interval = "delta")
compParm(weight_drm1, "slope", "-")

EDcomp(weight_drm1, c(50,50), type="absolute")
```


```{r}
ED(weight_drm1, c(50,90), type="absolute", interval = "delta") %>%
  as_tibble() %>%
  mutate(trt = c("38 cm soybean:50",
                 "38 cm soybean:90",
                 "76 cm soybean:50",
                 "76 cm soybean:90",
                 "Corn:50",
                 "Corn:90",
                 "Fallow:50",
                 "Fallow:90")) %>%
  ggplot(aes(x=fct_reorder(trt, Estimate), y=Estimate, color=trt)) +
  geom_errorbar(aes(ymin = Lower, ymax=Upper)) +
  geom_point() + coord_flip()
```


```{r message=FALSE, warning=FALSE, include=FALSE}
newdataa <- expand.grid(tpl_1=exp(seq(log(1), log(50), length=50)))

newdataa1 <- data.frame(crop =c("Corn"), newdataa)
newdataa2 <- data.frame(crop =c("38 cm soybean"), newdataa)
newdataa3 <- data.frame(crop =c("76 cm soybean"), newdataa)
newdataa4 <- data.frame(crop =c("Fallow (Control)"), newdataa)
ndd <- rbind(newdataa1, newdataa2, newdataa3, newdataa4)


pmm <- predict(weight_drm1, newdata = ndd, interval="confidence")

ndd$p <- pmm[,1]
ndd$pmin <- pmm[,2]
ndd$pmax <- pmm[,3]

data$tpl_11 = data$tpl_1
data$tpl_11[data$tpl_11 == 0] <- 0.5
```


```{r}
weight <- ggplot(data, aes(x=tpl_1, y=weight_reduction_crop, fill = crop, color=crop)) + 
  
  #geom_ribbon(data=ndd, aes(x=tpl_1, y=p, ymin=pmin, ymax=pmax), alpha=0.25) + 
  geom_line(data=ndd, aes(x=tpl_1, y=p)) + scale_fill_brewer(palette = "Set1") +
  stat_summary(geom = "point", fun.y = "mean", size = 2) +
  geom_jitter(aes(size=weight_g), alpha=0.2, width = 3) +
  theme_clean() +
  ylim(-10,110)
  #coord_trans(x = "log")

weight
```